window.Quest = {};
Quest.levels = [
{id:1,world:1,title:'Hola, mundo',concept:'console.log()',heading:'Toda aventura empieza con un hola.',description:'Despierta la magia del bosque con tu primera línea de JavaScript.',lesson:'console.log() muestra un mensaje en la consola. El texto va entre comillas y los paréntesis rodean el mensaje.',objective:'Escribe «Hola mundo» en la consola para abrir la puerta del bosque.',starterCode:'// Tu primera línea de magia ✨\nconsole.log("Hola mundo");',hints:['La puerta espera un saludo. Escribe un mensaje en la consola.','Usa console.log() y coloca el saludo entre comillas.','Prueba: console.log("Hola mundo");'],hero:{x:3,y:5},enemies:[],items:[],door:{x:7,y:5},winCondition:'greeting',requiredConcepts:['log'],rewards:{xp:100,coins:25},solution:'console.log("Hola mundo");'},
{id:2,world:1,title:'Un pequeño paso',concept:'Movimiento',heading:'Tu código también puede abrir caminos.',description:'Cada llamada a hero.moveRight() mueve al aprendiz una casilla.',lesson:'hero es tu personaje. Un método, como moveRight(), es una acción que puede realizar. Escribe las acciones en el orden en que quieras verlas.',objective:'Avanza tres casillas a la derecha y recoge la gema con hero.collect().',starterCode:'// El camino empieza aquí\nhero.moveRight();\n\n// Sigue hasta la gema y recógela\n',hints:['La gema está tres casillas a tu derecha.','Puedes repetir hero.moveRight(); y luego usar hero.collect();.','Escribe tres veces hero.moveRight(); y termina con hero.collect();.'],hero:{x:3,y:5},enemies:[],items:[{x:6,y:5,type:'gem'}],door:null,winCondition:'collect',requiredConcepts:['call'],rewards:{xp:100,coins:25},solution:'hero.moveRight();hero.moveRight();hero.moveRight();hero.collect();'},
{id:3,world:1,title:'Guarda una idea',concept:'Variables · let',heading:'Una variable es un pequeño cofre de ideas.',description:'Guarda un número en pasos y úsalo para recorrer el camino.',lesson:'let crea una variable: let pasos = 3; guarda el número 3 con el nombre pasos. hero.moveRight(pasos) utiliza ese número para dar varios pasos.',objective:'Crea la variable pasos con let, avanza tres casillas y recoge el cofre.',starterCode:'// Guarda cuántos pasos necesitas\nlet pasos = 1;\n\nhero.moveRight(pasos);\nhero.collect();',hints:['Puedes guardar el número de pasos en una variable.','El cofre está tres casillas a la derecha. Cambia el valor de pasos.','Usa let pasos = 3; antes de hero.moveRight(pasos); y hero.collect();.'],hero:{x:3,y:5},enemies:[],items:[{x:6,y:5,type:'chest'}],door:null,winCondition:'variableCollect',requiredConcepts:['let'],rewards:{xp:120,coins:30},solution:'let pasos = 3;hero.moveRight(pasos);hero.collect();'},
{id:4,world:1,title:'El primer slime',concept:'Combate',heading:'Respira. Este slime es más tímido de lo que parece.',description:'hero.attack() ataca a un enemigo que esté en una casilla vecina.',lesson:'Tu ataque hace 25 puntos de daño. Este slime tiene 50 de vida, así que necesitarás dos ataques. Los slimes contraatacan: observa tu barra de vida.',objective:'Derrota al slime con dos ataques. Tu héroe debe seguir en pie.',starterCode:'// Un ataque es un buen comienzo\nhero.attack();\n\n// ¿Cuánta vida le queda al slime?\n',hints:['El slime tiene 50 de vida. Cada ataque quita 25.','Necesitas atacar dos veces.','Escribe hero.attack(); en dos líneas.'],hero:{x:4,y:5},enemies:[{id:1,x:5,y:5,health:50,damage:12}],items:[],door:null,winCondition:'defeat',requiredConcepts:['call'],rewards:{xp:120,coins:30},solution:'hero.attack();hero.attack();'},
{id:5,world:1,title:'Decide tu camino',concept:'Condicionales · if',heading:'A veces, la mejor magia es tomar una decisión.',description:'Comprueba si el enemigo está cerca antes de atacar.',lesson:'if ejecuta el código entre llaves solo cuando la condición es verdadera. enemy.isNear() devuelve true si hay un slime al alcance, o false si no lo hay.',objective:'Usa if (enemy.isNear()) para atacar y derrotar al slime cercano.',starterCode:'// Pregunta antes de actuar\nif (enemy.isNear()) {\n  // Escribe tu ataque aquí\n\n}',hints:['El slime está cerca. El código dentro del if puede atacarlo.','Coloca hero.attack(); dentro de las llaves { }.','if (enemy.isNear()) { hero.attack(); }'],hero:{x:4,y:5},enemies:[{id:1,x:5,y:5,health:25,damage:10}],items:[],door:null,winCondition:'conditionalDefeat',requiredConcepts:['if'],rewards:{xp:140,coins:35},solution:'if (enemy.isNear()) { hero.attack(); }'},
{id:6,world:1,title:'La primera horda',concept:'Bucles · for',heading:'Una sola idea. Cinco veces más poderosa.',description:'Sobrevive a tres oleadas y descubre el poder de repetir con un bucle.',lesson:'for repite un bloque. let i = 0 inicia un contador; i < 5 lo mantiene activo cinco veces; i++ suma uno tras cada vuelta. Aquí cada ataque vence a un slime. Las oleadas llegan solas.',objective:'Vence las tres oleadas (1, 2 y 2 slimes). Usa un bucle for para tus cinco ataques.',starterCode:'// Un bucle multiplica tu magia\nfor (let i = 0; i < 3; i++) {\n  hero.attack();\n}',hints:['Llegarán cinco slimes en total, repartidos en tres oleadas.','Cada vuelta del bucle vence a un slime. Necesitas cinco vueltas.','Cambia la condición a i < 5 en el bucle for.'],hero:{x:4,y:5},enemies:[{id:1,x:5,y:5,health:25,damage:8}],waves:[[{id:2,x:5,y:5,health:25,damage:8},{id:3,x:4,y:4,health:25,damage:8}],[{id:4,x:5,y:5,health:25,damage:8},{id:5,x:4,y:4,health:25,damage:8}]],items:[],door:null,winCondition:'loopDefeat',requiredConcepts:['for'],rewards:{xp:200,coins:50},solution:'for (let i = 0; i < 5; i++) { hero.attack(); }'}
];
Quest.map = ['TTTTTTTTTTTT','TTTggggggTTT','TTgggggggTTT','TTggggggggTT','TTggppppggTT','TTgppppppgTT','TTggppppggTT','TTgggggggTTT'];

Quest.levels.forEach(level=>{level.map=Quest.map;level.worldName='El Bosque de JavaScript';});
