Quest.UI = class {
 constructor(){this.editor=document.getElementById('codeEditor');this.console=document.getElementById('console');this.dialog=document.getElementById('infoDialog');this.win=document.getElementById('winDialog');this.editor.addEventListener('input',()=>this.lines());this.editor.addEventListener('scroll',()=>document.getElementById('lineNumbers').scrollTop=this.editor.scrollTop);this.editor.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const start=this.editor.selectionStart,end=this.editor.selectionEnd;this.editor.setRangeText('  ',start,end,'end');this.lines()}});document.getElementById('closeInfo').onclick=()=>this.dialog.close();for(const d of [this.dialog,this.win])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})}
 lines(){document.getElementById('lineNumbers').textContent=this.editor.value.split('\n').map((_,i)=>i+1).join('\n')}
 log(message,type=''){const p=document.createElement('p');p.className=type;p.textContent=(type==='error'?'! ':type==='success'?'✓ ':type==='output'?'> ':'')+message;this.console.append(p);while(this.console.children.length>80)this.console.firstChild.remove();this.console.scrollTop=this.console.scrollHeight}
 clear(){this.console.replaceChildren()}
 load(level){document.getElementById('levelTitle').textContent=level.title;document.getElementById('levelKicker').textContent='NIVEL '+String(level.id).padStart(2,'0');document.getElementById('sceneLevel').textContent=String(level.id).padStart(2,'0');document.getElementById('lessonHeading').textContent=level.heading;document.getElementById('lessonText').textContent=level.description;document.getElementById('objectiveText').textContent=level.objective;document.getElementById('rewardText').textContent='✦ +'+level.rewards.xp+' XP   ◈ +'+level.rewards.coins;this.editor.value=level.starterCode;this.lines();this.health(100);document.getElementById('speechBubble').hidden=true;this.clear();this.log('El bosque está listo. ¡Prueba tu código!');}
 stats(progress,current){const d=progress.data;document.getElementById('xpStat').textContent='✦ '+d.xp+' XP';document.getElementById('coinStat').textContent='◈ '+d.coins;document.getElementById('starStat').textContent='★ '+progress.stars;const count=Object.keys(d.completed).length;document.getElementById('progressText').textContent=count+' de 6 completados';document.getElementById('progressFill').style.width=count/6*100+'%';document.getElementById('soundButton').textContent='♫ Sonido '+(d.settings.sound?'activado':'apagado');const list=document.getElementById('levelList');list.replaceChildren();Quest.levels.forEach(l=>{const b=document.createElement('button');const unlocked=progress.unlocked(l.id);b.className='level-button '+(l.id===current?'active ':'')+(d.completed[l.id]?'completed ':'')+(!unlocked?'locked':'');b.disabled=!unlocked;b.setAttribute('aria-label','Nivel '+l.id+': '+l.title+(!unlocked?', bloqueado':''));if(l.id===current)b.setAttribute('aria-current','step');b.innerHTML='<span class="node">'+(d.completed[l.id]?'✓':unlocked?String(l.id).padStart(2,'0'):'⌑')+'</span><span class="level-copy"><strong>'+l.title+'</strong><small>'+(d.completed[l.id]?'★'.repeat(d.completed[l.id]):l.concept)+'</small></span>';b.onclick=()=>Quest.app.select(l.id);list.append(b)})}
 health(hp){document.getElementById('healthFill').style.width=Math.max(0,hp)+'%';document.getElementById('healthFill').style.background=hp<35?'#da8760':'#69a75f';document.getElementById('healthText').textContent=hp+' / 100'}
 info(html){document.getElementById('infoContent').innerHTML=html;if(!this.dialog.open)this.dialog.showModal()}
 speech(message){const bubble=document.getElementById('speechBubble');bubble.textContent=message;bubble.hidden=false;clearTimeout(this.speechTimer);this.speechTimer=setTimeout(()=>bubble.hidden=true,2300)}
 busy(value){for(const id of ['runButton','resetButton','hintButton'])document.getElementById(id).disabled=value;document.getElementById('runButton').innerHTML=value?'Magia en marcha…':'<span>▶</span> Ejecutar código';this.editor.readOnly=value;for(const b of document.querySelectorAll('.level-button'))if(value)b.disabled=true;else b.disabled=!Quest.app.progress.unlocked(Number(b.getAttribute('aria-label').match(/\d+/)[0]));}
 celebrate(level,stars,isNew){document.getElementById('winStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);document.getElementById('winMessage').textContent=level.id===6?'¡Completaste el bosque! Ya sabes saludar, moverte, guardar ideas, decidir y repetir.':'Tu código acaba de hacer magia. Sigue explorando, una línea a la vez.';document.getElementById('winRewards').textContent=isNew?'✦ +'+level.rewards.xp+' XP     ◈ +'+level.rewards.coins+' monedas':'Tu mejor puntuación queda guardada';document.getElementById('nextButton').textContent=level.id===6?'Volver al mapa':'Siguiente nivel';this.win.showModal();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)for(let i=0;i<30;i++){const el=document.createElement('i');el.className='spark';el.style.left=(35+Math.random()*30)+'vw';el.style.top='15vh';el.style.background=['#d7ed80','#ddb955','#91b88f'][i%3];el.style.setProperty('--dx',(Math.random()*500-250)+'px');el.style.animationDelay=(Math.random()*.3)+'s';document.body.append(el);setTimeout(()=>el.remove(),2300)}}
};
